# Generated by Django 5.2.6 on 2026-02-06 02:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro de devis')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client_nom', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du client')),
                ('client_telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone du client')),
                ('client_adresse', models.TextField(blank=True, null=True, verbose_name='Adresse du client')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes/Observations')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.PositiveIntegerField(verbose_name='N°')),
                ('libelle', models.CharField(max_length=500, verbose_name='Libellé')),
                ('unite', models.CharField(choices=[('piece', 'Pièce'), ('m2', 'm²'), ('m3', 'm³'), ('kg', 'Kg'), ('tonne', 'Tonne'), ('litre', 'Litre'), ('metre', 'Mètre'), ('heure', 'Heure'), ('jour', 'Jour'), ('forfait', 'Forfait')], default='piece', max_length=20, verbose_name='Unité')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix Unitaire (P.U)')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='mabipint.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'ordering': ['numero_ligne'],
                'unique_together': {('devis', 'numero_ligne')},
            },
        ),
    ]
