# Generated by Django 5.2.6 on 2026-02-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabipint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire'), ('virement', 'Virement'), ('cheque', 'Chèque')], max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_cours', max_length=20, verbose_name='Statut'),
        ),
    ]
