# Generated by Django 5.2.8 on 2026-03-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabipint', '0002_devis_mode_paiement_alter_devis_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces')], default='especes', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('paye', 'Payé')], default='paye', max_length=20, verbose_name='Statut'),
        ),
    ]
