# Generated by Django 5.2.8 on 2026-03-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabipint', '0003_alter_devis_mode_paiement_alter_devis_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(choices=[('gramme', 'g'), ('kg', 'Kg'), ('litre', 'Litre')], default='kg', max_length=20, verbose_name='Unité'),
        ),
    ]
