# Generated by Django 5.2.8 on 2026-03-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabipint', '0004_alter_lignedevis_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(choices=[('gramme', 'g'), ('kg', 'Kg'), ('litre', 'Litre')], default='gramme', max_length=20, verbose_name='Unité'),
        ),
    ]
