# Generated by Django 5.2.8 on 2026-03-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabipint', '0005_alter_lignedevis_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='inclure_main_oeuvre',
            field=models.BooleanField(default=True, verbose_name="Inclure la main d'œuvre (25%)"),
        ),
    ]
