# Generated by Django 5.2.8 on 2026-03-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabipint', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
        migrations.AlterModelOptions(
            name='lignedevis',
            options={'ordering': ['numero_ligne'], 'verbose_name': 'Ligne de vente', 'verbose_name_plural': 'Lignes de vente'},
        ),
        migrations.AddField(
            model_name='devis',
            name='service',
            field=models.CharField(choices=[('mabipeint', 'MABIPEINT'), ('cleaning', 'SHAMMAR CLEANING')], default='mabipeint', max_length=20, verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_service',
            field=models.CharField(choices=[('mabipeint', 'MABIPEINT'), ('cleaning', 'SHAMMAR CLEANING')], default='mabipeint', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(choices=[('gramme', 'g'), ('kg', 'Kg'), ('litre', 'Litre'), ('unite', 'U'), ('heure', 'Heure'), ('m2', 'm²')], default='unite', max_length=20, verbose_name='Unité'),
        ),
    ]
