# Generated by Django 5.2.8 on 2026-03-26 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabipint', '0008_alter_devis_options_alter_lignedevis_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='lignedevis',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='lignedevis',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='devis',
            name='client_adresse',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='mode_paiement',
        ),
        migrations.AddField(
            model_name='devis',
            name='engin_marque',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type & Marque Engin'),
        ),
        migrations.AddField(
            model_name='devis',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Matricule'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='client_telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='inclure_main_oeuvre',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='service',
            field=models.CharField(choices=[('mabipeint', 'MABIPEINT'), ('cleaning', 'SHAMMAR CLEANING')], default='mabipeint', max_length=20),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('paye', 'Payé')], default='paye', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='mabipint.devis'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='libelle',
            field=models.CharField(max_length=500, verbose_name='Désignation / Service'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='numero_ligne',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(default='unite', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
