# Generated by Django 5.2.8 on 2026-03-26 17:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabipint', '0009_alter_devis_options_alter_lignedevis_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
        migrations.AlterModelOptions(
            name='lignedevis',
            options={'ordering': ['numero_ligne'], 'verbose_name': 'Ligne de vente', 'verbose_name_plural': 'Lignes de vente'},
        ),
        migrations.RemoveField(
            model_name='devis',
            name='engin_marque',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='matricule',
        ),
        migrations.AddField(
            model_name='devis',
            name='client_adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse du client'),
        ),
        migrations.AddField(
            model_name='devis',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du client'),
        ),
        migrations.AddField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces')], default='especes', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='client_telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone du client'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='inclure_main_oeuvre',
            field=models.BooleanField(default=True, verbose_name="Inclure la main d'œuvre (25%)"),
        ),
        migrations.AlterField(
            model_name='devis',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes/Observations'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numéro de devis'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='service',
            field=models.CharField(choices=[('mabipeint', 'MABIPEINT'), ('cleaning', 'SHAMMAR CLEANING')], default='mabipeint', max_length=20, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('paye', 'Payé')], default='paye', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='mabipint.devis', verbose_name='Devis'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='libelle',
            field=models.CharField(max_length=500, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='numero_ligne',
            field=models.PositiveIntegerField(verbose_name='N°'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix Unitaire (P.U)'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(choices=[('gramme', 'g'), ('kg', 'Kg'), ('litre', 'Litre'), ('unite', 'U'), ('heure', 'Heure'), ('m2', 'm²')], default='unite', max_length=20, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterUniqueTogether(
            name='lignedevis',
            unique_together={('devis', 'numero_ligne')},
        ),
    ]
