# Generated by Django 5.2.8 on 2026-03-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabipint', '0010_alter_devis_options_alter_lignedevis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('bancaire', 'Bancaire')], default='especes', max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
