# Generated by Django 5.2.8 on 2026-03-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mabipint', '0011_alter_devis_mode_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestationCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la prestation')),
                ('prix_par_defaut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par défaut')),
            ],
            options={
                'verbose_name': 'Prestation Cleaning',
                'verbose_name_plural': 'Prestations Cleaning',
            },
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='type_prestation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de prestation'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='unite',
            field=models.CharField(default='unite', max_length=50, verbose_name='Unité/Plaque'),
        ),
    ]
